# Generated by Django 5.2.8 on 2025-12-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_category_id_alter_notifications_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskactivity',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tasknotification',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasknotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
        migrations.DeleteModel(
            name='TaskActivity',
        ),
        migrations.DeleteModel(
            name='TaskNotification',
        ),
    ]
